name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # مرحله ۱: کد رو از گیت‌هاب می‌کشه پایین
      - name: Checkout code
        uses: actions/checkout@v4

      # مرحله ۲: جاوا رو نصب می‌کنه (نسخه رو مطابق پروژه‌ت بگذار)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # مرحله ۳: پروژه رو با Maven بیلد می‌کنه
      - name: Build with Maven
        run: ./mvnw.cmd clean package -DskipTests

      # مرحله ۴: Docker Image جدید می‌سازه
      - name: Build Docker Image
        run: docker build -t product-service:latest .

      # مرحله ۵: توی Kubernetes، دیپلویمنت رو با ایمیج جدید آپدیت می‌کنه
      - name: Restart Deployment in Kubernetes
        run: kubectl rollout restart deployment product-service