name: Test Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from my own computer! "